accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('mywallet', views.MyWalletView.as_view(), name='wallet'),
    path('movement', views.MovementListView.as_view(), name='movement'),
    path('roleta', views.GameView.as_view(), name='roleta'),
    path('postbets', views.post_bets, name='postbets'),
    path('postcoins', views.post_coins, name='postcoins')
]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.conf import settings
from django.db.models import F
from django.db.models.signals import post_save
from django.dispatch import receiver


class Wallet(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True
    )
    total_caiocoins = models.FloatField(default=0)

class Movement(models.Model):
    created_at = models.DateField(
        auto_now_add=True,
    )

    wallet = models.ForeignKey(
        Wallet,
        on_delete=models.CASCADE
    )
    
    description = models.TextField(
        
    )
    
    value = models.FloatField(

    )

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def update_stock(sender, instance, created, raw, **kwargs):
    if not created or raw:
        return
    Wallet.objects.create(user=instance)

@receiver(post_save, sender=Movement)
def update_wallet(instance, created, raw, **kwargs):
    if raw or not created:
        return

    wallet = instance.wallet
    wallet.total_caiocoins = F('total_caiocoins') + instance.value
    wallet.save()

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

main/views.py
from typing import Any
import json
from django.http import HttpRequest
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views import generic
from .models import Wallet, Movement
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, Http404
from django.views.decorators.csrf import csrf_exempt
from roleta import Roleta, Dealer
from django.conf import settings


def update_user_movement(user_id, value, movement_description):
    if value == 0:
        return

    wallet = Wallet.objects.filter(user=user_id).first()
    new_movement = Movement(wallet=wallet, 
                            description=movement_description,
                            value=value)
    new_movement.save()

    return True

class MyWalletView(LoginRequiredMixin, generic.DetailView):
    model = Wallet
    template_name = "wallet/wallet.html"

    def get_object(self):
        return super().get_queryset().get(user=self.request.user)

class MovementListView(LoginRequiredMixin, generic.ListView):
    model = Movement
    template_name = "movements/list.html"

    def get_queryset(self):
        return super().get_queryset().filter(wallet__user=self.request.user).order_by('-pk')
    
class GameView(LoginRequiredMixin, generic.TemplateView):
    template_name = "games/roleta.html"

def get_coins_by_ids(ids):
    id_coins = {}

    for id in ids:
        id_coins['id'] = id
        id_coins['coins'] = f"{(Wallet.objects.filter(user=id).first().total_caiocoins):.1f}"

    return id_coins

@csrf_exempt
def post_bets(request: HttpRequest):
    if request.method != "POST":
        raise Http404()
    
    roleta = Roleta.create_default()

    data = json.loads(request.body.decode())
    dealer = Dealer.create_from_inputs(data)

    unique_ids = set(map(lambda x: x['id'], data))

    for input in dealer.inputs:
        update_user_movement(input['id'], -input['value'], 'Bet')

    before_bet = get_coins_by_ids(unique_ids)

    secret_number = roleta.pick()
    computed_bets = dealer.compute_bets(secret_number)
    won = False
    for bet in computed_bets:
        state = update_user_movement(bet['id'], bet['value'], 'Won')
        if state:
            won = True

    after_bet = get_coins_by_ids(unique_ids)

    obj = {
        'secret_number': secret_number,
        'before_bet': before_bet,
        'after_bet': after_bet,
        'won': won
    }

    return JsonResponse(obj)

@csrf_exempt
def post_coins(request: HttpRequest):
    if request.method != "POST":
        raise Http404()
    
    data = json.loads(request.body.decode())

    update_user_movement(data['user_id'], data['value'], 'Add')

    user_coins = Wallet.objects.filter(user=data['user_id']).first().total_caiocoins 
    formatted_coins = f'{user_coins:.2f}'
    formatted_coins = formatted_coins.replace('.', ',')

    obj = {
        'coins': formatted_coins
    }

    return JsonResponse(obj)

main/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/geral.css' %}">
    <link rel="stylesheet" href="{% static 'main/header.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/login.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/signup.css' %}">
    <link rel="stylesheet" href="{% static 'wallet/movement-list.css' %}">
    <link rel="stylesheet" href="{% static 'wallet/wallet.css' %}">
    <link rel="stylesheet" href="{% static 'games/roleta.css' %}">
    <title>Caiossino</title>

    {% block head-roleta %}     
        
    {% endblock %}

</head>
<body>
    <section>
        {% block header %}
            {% include "header.html" %}
        {% endblock %}
    </section>
    
    <section>
        {% block content %}

        {% endblock %}
    </section>


    {% block script %}
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        <script src="{% static 'scripts/main.js' %}"></script>
    {% endblock %}

</body>
</html>

main/templates/header.html
<header class="header__container">
    <div class="header__content">
        <div>
            <h1 class="header__title">
                <a href="{% url 'roleta' %}">Caiossino</a>
            </h1>
        </div>

        <div>
            <a href="{% url 'wallet' %}">
                <div class="header__login header__account{% if user.is_authenticated %}  {% else %} header__details {% endif %}">
                    <div>
                        <svg width="30" height="31" viewBox="0 0 30 31" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g clip-path="url(#clip0_2_492)">
                                <path d="M7.30774 30.945C7.08177 30.8995 6.85508 30.8562 6.62985 30.8078C4.48542 30.3434 3.05115 28.7793 2.79658 26.596C2.64545 25.2982 2.76283 24.0048 2.94477 22.718C3.10324 21.597 3.34754 20.4943 3.79506 19.4489C4.39004 18.0586 5.19705 16.8393 6.58143 16.1005C7.43539 15.6449 8.35097 15.427 9.30837 15.4461C9.61063 15.452 9.9283 15.606 10.2042 15.7564C10.6487 15.9985 11.0625 16.2949 11.4917 16.5656C12.7888 17.3822 14.193 17.8231 15.7351 17.7043C16.8605 17.6177 17.9008 17.2406 18.8648 16.6559C19.2067 16.4483 19.5603 16.2516 19.8691 16.0022C20.6534 15.3683 21.5235 15.3625 22.4464 15.565C24.2174 15.9545 25.4448 17.019 26.2907 18.5861C27.0053 19.9096 27.3897 21.3358 27.5577 22.8133C27.6817 23.9057 27.7396 25.0106 27.7389 26.1103C27.7382 28.4646 26.1183 30.3698 23.8029 30.8203C23.5953 30.8606 23.3884 30.9032 23.1815 30.945H7.30774ZM15.2142 29.1887C16.1709 29.1887 17.1275 29.1887 18.0835 29.1887C19.5962 29.1872 21.1097 29.2143 22.6218 29.1769C24.8087 29.1234 26.0273 27.8468 25.9884 25.6657C25.973 24.7993 25.9173 23.9299 25.8116 23.0708C25.6554 21.8002 25.3568 20.5618 24.7324 19.4239C24.1602 18.3814 23.3796 17.5993 22.1786 17.3147C21.6541 17.1907 21.1706 17.1724 20.7238 17.5524C20.481 17.7593 20.1912 17.9119 19.9176 18.0806C17.2075 19.7496 14.3984 19.9785 11.5115 18.592C10.7867 18.2435 10.1257 17.7622 9.43089 17.3484C9.32672 17.2861 9.19906 17.2215 9.08461 17.2259C8.06779 17.2641 7.18595 17.614 6.49559 18.3887C5.84045 19.1231 5.42815 19.9888 5.14056 20.9183C4.64535 22.5177 4.50889 24.1676 4.50303 25.8286C4.49936 26.921 4.8317 27.8835 5.77002 28.5511C6.47799 29.0544 7.28793 29.1857 8.12868 29.1872C10.491 29.1916 12.8526 29.1887 15.2149 29.1887H15.2142Z" fill="#fff"></path>
                                <path d="M22.2931 8.1992C22.2953 12.1924 18.9903 15.4468 15.0308 15.4087C10.9716 15.3698 7.81838 12.1308 7.83158 8.08181C7.84332 4.19058 11.1807 0.866454 15.1636 0.946421C19.1143 1.02565 22.3269 4.25661 22.2931 8.1992ZM20.5155 8.17279C20.5735 5.23015 18.0725 2.68808 15.0484 2.70936C12.0185 2.73064 9.56958 5.1876 9.59379 8.197C9.61873 11.2357 12.0214 13.6252 15.0579 13.6311C18.1011 13.6369 20.5236 11.2145 20.5155 8.17279Z" fill="#fff"></path>
                            </g>
                            <defs>
                            <clipPath id="clip0_2_492">
                                <rect width="30" height="30" transform="translate(0 0.945007)"></rect>
                            </clipPath>
                            </defs>
                        </svg>
                    </div>
                    
                    {% if user.is_authenticated %}
                        {{ user.username }}
                        <div class="header__popup">
                            <form action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Log Out</button>
                            </form>
                        </div>    
                    {% else %}
                        <a href="{% url 'login' %}" class='header__login login'>Log In</a>
                    {% endif %}
                </div>
            </a>
        </div>
    </div>
</header>
    

main/templates/movements/list.html
{% extends 'base.html' %}
{% block content %}

{% load l10n %}

<div class="bet__list">
{% for object in object_list %}
  <div id="bets__container">
    <div id="bet__container" class="{% if object.value < 0 %} bet__color {% else %} win__color {% endif %}">
      <div class="bet__content">
        <p>{{ object.description }}</p>
        <p>R${% if object.value < 0 %}{{ object.value|localize|slice:"1:" }}{% else %}{{ object.value|localize }}{% endif%}</p>
      </div>
    </div>

    <div id="detail__container">
      <div class="detail__content">
        <p>
          ID: #{{ object.pk }}
          {{ object.created_at}}
        </p>
      </div>
    </div>
  </div>
{% endfor %}
</div>

{% endblock %}

main/templates/wallet/wallet.html
{% extends "base.html" %}
{% block content %}

{% load l10n humanize %}
<h1 id="caiocoins_h1">SEUS CAIOCOINS C$<span id="caiocoins">{{ object.total_caiocoins|floatformat:2|localize }}</span> </h1>

<div id="div_quantia">
    <input type="number" name="Quantia" id="iQuantia" min='1'>
    <button id="bQuantia">
        Adicionar "Fundos"
    </button>
</div>

<div class="bet__list">
    {% for object in object.movement_set.all|dictsortreversed:"pk"|slice:"5" %}
      <div id="bets__container">
        <div id="bet__container" class="{% if object.value < 0 %} bet__color {% else %} win__color {% endif %}">
          <div class="bet__content">
            <p>{{ object.description }}</p>
            <p>R${% if object.value < 0 %}{{ object.value|localize|slice:"1:" }}{% else %}{{ object.value|localize }}{% endif%}</p>
          </div>
        </div>
    
        <div id="detail__container">
          <div class="detail__content">
            <p>
              ID: #{{ object.pk }}
              {{ object.created_at}}
            </p>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>

<br>

<a href="{% url 'movement' %}" id="mvmnt_button">Ver Mais</a>

{% endblock %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.7.1.min.js"
    integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script>
    $(document).on('click', '#bQuantia', function (e) {
        let objResposta = {}
        let valor = $('#iQuantia')[0].value
        objResposta.user_id = "{{ request.user.id }}"
        objResposta.value = valor
        console.log(objResposta)
        $.ajax({
            url: "{% url 'postcoins' %}",
            method: "POST",
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify(objResposta),
            success: (function (data, status) {
                $('#caiocoins')[0].innerText = data.coins
                location.reload();
            })
        })
    })

</script>
{% endblock %}